const STATUS_OK = 200;
const STATUS_CREATED = 201;
const ERROR_INCORRECT_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  STATUS_OK,
  STATUS_CREATED,
  ERROR_INCORRECT_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
};
